config/routes.rb
ThePool::Application.routes.draw do
    
  get "static_pages/help"

  get "static_pages/home"

  get "static_pages/index"

devise_for :users

devise_for :admin_users, ActiveAdmin::Devise.config
  resources :bets

  ActiveAdmin.routes(self)

  root :to => 'static_pages#home'

  match 'new' => 'bets#new'
  match 'register' => 'devise/registrations#new'
  match '/signin' => 'devise/sessions#new'
  match 'signout' => 'devise/sessions#destroy', :method => :delete
  match 'help' => 'static_pages#help'
  match 'home' => 'static_pages#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  attr_accessible :user_id, :divorce, :divorced_by, :engagement, :new_wedding, :postponement, :wedding

  validates  :divorce, :divorced_by, :engagement, :new_wedding, :postponement, :wedding, :presence => true

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :display_name, :remember_me, :bet_id
  has_one :bet
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

 def after_sign_in_path_for(resource)
    new_bet_path # <- Path you want to redirect the user to.
  end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  # GET /bets
  # GET /bets.json

  
  def index
    @bets = Bet.all
    
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bets }
    end
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
    @bet = Bet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bet }
    end
  end

  # GET /bets/new
  # GET /bets/new.json
  def new
    @bet = Bet.new(user_id: params[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bet }
    end
  end

  # GET /bets/1/edit
  def edit
    @bet = Bet.find(params[:id])
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(params[:bet])
    @bet.user_id = current_user.id
    @bet.displayname = current_user.display_name

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render json: @bet, status: :created, location: @bet }
      else
        format.html { render action: "new" }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bets/1
  # PUT /bets/1.json
  def update
    @bet = Bet.find(params[:id])

    respond_to do |format|
      if @bet.update_attributes(params[:bet])
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy

    respond_to do |format|
      format.html { redirect_to bets_url }
      format.json { head :no_content }
    end
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bets/_form.html.erb
<form class="form hero-unit">
<%= semantic_form_for(@bet) do |f| %>
  <%= f.inputs do %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      
<fieldset>
  <div class="field">

    <%= f.input :engagement, :label => "They'll be engaged by the end of:", :as => :date_select, :start_month => Time.now.month, :start_year => Time.now.year, :end_year => Time.now.year + 10, :order => [:month, :year] %><br />
  </div>
  <div class="field">
    <%= f.input :wedding, :label => 'The wedding will be by the end of:', :as => :date_select, :start_year => Time.now.year, :end_year => Time.now.year + 10, :order => [:month, :year] %><br />
  </div>
  <div class="field">
    <%= f.input :postponement, :label => 'Will they postpone the wedding?', :as => :radio, :collection => ['Yes', 'No'], :selected =>'Yes' %><br />
    
  </div>
  <div class="field">
    <%= f.input :new_wedding, :label => 'New wedding will be by the end of:', :as => :date_select, :start_year => Time.now.year, :end_year => Time.now.year + 10, :order => [:month, :year]  %><br />
  </div>
  <div class="field">
   <%= f.input :divorce, :label => 'Will they get divorced?', :as => :radio, :collection => ['Yes', 'No'] %><br />
  </div>
  <div class="field">
    <%= f.input :divorced_by, :label => 'They be divorced by the end of:', :as => :date_select, :start_year => Time.now.year, :end_year => Time.now.year + 10, :order => [:month, :year] %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  </fieldset>
  <% end %>
<% end %>
</form>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<h1 style="margin: 75px 0 40px 0;">Here's what everyone else thinks</h1>

<table class="hero-unit">
  <tr>
    <th>Bet ID</th>
    <th>Display Name</th>
    <th>Engaged By?</th>
    <th>Married By?</th>
    <th>Wedding Postponed?</th>
    <th>New Married By?</th>
    <th>Divorced?</th>
    <th>Divorced By?</th>
  </tr>

<% @bets.each do |bet| %>


  <tr>
    <td><%= bet.id %></td>
    <td><%= bet.displayname %></td>
    <td>Last day of <%= bet.engagement.strftime("%b, %Y") %></td>
    <td>Last day of <%= bet.wedding.strftime("%b, %Y") %></td>
    <td><%= bet.postponement %></td>
    <td>Last day of <%= bet.new_wedding %></td>
    <td><%= bet.divorce %></td>
    <td>Last day of <%= bet.divorced_by.strftime("%b, %Y") %></td>
    <td><%= link_to 'Show', bet %></td>
    <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
    <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

</table>

<% @bets.each do |bet| %>

<table class="hero-unit">
  <tr>
    <th class="pull-left" style="padding: 10px 0 0 10px;">Bet ID</th>
        <tr>
            <td style="padding: 0 0 0 10px;"><%= bet.id %></td>
        </tr>
    <th class="pull-left" style="padding: 10px 0 0 10px;">Display Name</th>
        <tr>
            <td style="padding: 0 0 0 10px;"><%= bet.displayname %></td>
        </tr>
    <th class="pull-left" style="padding: 10px 0 0 10px;">Engaged By?</th>
        <tr>
            <td style="padding: 0 0 0 10px;">Last day of <%= bet.engagement.strftime("%b, %Y") %></td>
        </tr>
    <th class="pull-left" style="padding: 10px 0 0 10px;">Married By?</th>
        <tr>
            <td style="padding: 0 0 0 10px;">Last day of <%= bet.wedding.strftime("%b, %Y") %></td>
        </tr>
    <th class="pull-left" style="padding: 10px 0 0 10px;">Wedding Postponed?</th>
        <tr>
            <td style="padding: 0 0 0 10px;"><%= bet.postponement %></td>
        </tr>
    <th class="pull-left" style="padding: 10px 0 0 10px;">New Married By?</th>
        <tr>
            <td style="padding: 0 0 0 10px;">Last day of <%= bet.new_wedding %></td>
        </tr>
    <th class="pull-left" style="padding: 10px 0 0 10px;">Divorced?</th>
        <tr>
            <td style="padding: 0 0 0 10px;"><%= bet.divorce %></td>
        </tr>
    <th class="pull-left" style="padding: 10px 0 0 10px;">Divorced By?</th>
        <tr>
            <td style="padding: 0 0 10px 10px;">Last day of <%= bet.divorced_by.strftime("%b, %Y") %></td>
        </tr>
  </tr>

<% end %>

</table>


<br />

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<h1 style="margin: 75px 0 40px 0;">Place your bets</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThePool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

 

<% if user_signed_in? %>
<p class="lead pull-left" style="margin: 7px 0 0px 0;">What's up, <%= current_user.display_name %></p>
<% end %>

  <navigation>
    <ul class="nav nav-pills  pull-right" style="margin-top: 5px;">
      <li class="active">
      <li><%= link_to 'Home', root_path %></li>
      
      <% if user_signed_in? %>

      <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
      <li><%= link_to 'Place your bet', new_bet_path(user_id: @user) %></li>
      
      <% else %>
       <li><%= link_to 'Login or Register', new_user_registration_path %></li>
       <% end %>

      <li><%= link_to 'Help', help_path %></li>
    </ul>
  </navigation>

<%= yield %>

<footer class="text-center muted">
  Created by <%= link_to 'Jon Levine', 'http://www.jonlevine.com' %>. &copy; <%= Time.now.year %>

</footer>
 </div>
</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="hero-unit" style="margin-top: 50px;">
  <h1>Welcome to The Pool</h1>
  <p>Just a place where we can wager on the life of an idiot</p>
  <p>
    <% if user_signed_in? %>
    <a class="btn btn-primary btn-large" href=<%= new_bet_path %>>
      Place your bet
    </a>
      <% else %>
      
      <a class="btn btn-primary btn-large" href=<%= new_user_registration_path %>>
      Register
      </a>

      <a class="btn btn-success btn-large" href=<%= new_user_session_path %>>
      Login
      </a> 
 
      <% end %>
    
  </p>
</div>